E-commerce/eshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('accounts.urls')),
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E-commerce/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^category/(?P<cat_id>\d+)/$', views.category, name='category'),
    url(r'^category/(?P<cat_id>\d+)/page/(?P<page_number>\d+)/$', views.category, name='cat_page'),
    url(r'^search/$', views.search, name='search'),
]

E-commerce/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^product/(?P<product_id>\d+)/$', views.product, name='product'),
    url(r'^product/(?P<product_id>\d+)/add_comment/$', views.add_comment, name='add_comment'),
]

"""
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
"""

E-commerce/products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description = models.TextField(blank=True, null=True, default=None)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_date = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '%s %s' % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='product_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_date = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

E-commerce/products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseForbidden, Http404, JsonResponse
from django.utils import dateformat

from products.models import *
from accounts.models import Comment

def product(request, product_id):
    args = {}
    args['product'] = get_object_or_404(Product, id=product_id, is_active=True)
    args['comments'] = Comment.objects.filter(product__id=product_id).order_by('create_date')
    # print(args['comments'])
    return render(request, 'products/product.html', args)

def add_comment(request, product_id):
    if request.POST:
        if not request.user.is_authenticated():
            return HttpResponseForbidden()
        user = request.user
        data = request.POST
        product = get_object_or_404(Product, id=product_id, is_active=True)
        text = data.get('text')
        comment = Comment.objects.create(user=user, product=product, comment_text=text)
        username = comment.user.username
        if hasattr(user, 'first_name'):
            username = comment.user.first_name
            if hasattr(user, 'last_name'):
                username += ' ' + comment.user.last_name
        args = {
            'username': username,
            'date': dateformat.format(comment.create_date, 'd E Y г.'),
            'comment_text': comment.comment_text,
        }
        return JsonResponse(args)

    return Http404('No data provided')

E-commerce/templates/products/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-6 product-page-slider">
        {% for image_item in product.productimage_set.all %}
        <div class="photo">
          <img class="product-img-item center-block" src="{{ image_item.image.url }}"/>
        </div>
        {% endfor %}
      </div>
      <div class="col-lg-6">
        <h2 class="text-center">{{ product.name }}</h2>
        <div class="row">
          {{ product.description }}
        </div>
        <div class="row">
          <h5>Price: ${{ product.price }}</h5>
        </div>
        <div>
          <form id="form_buying_product" method="post" class="form-inline" action="{% url 'update_cart' %}">{% csrf_token %}
            <div class="form-group">
              <label for="count">Количество: </label>
              <input type="number" id="count" class="form-control" min="1" value="1">
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary"
                id="submit_btn"
                data-product_id="{{ product.id }}"
                data-product_name="{{ product.name }}"
                data-product_price="{{ product.price }}">
                <span class="glyphicon glyphicon-shopping-cart"></span> Добавить в корзину
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="row">
      {% if comments %}
        {% for comment in comments %}
          <div class="row">
            <h4><b>{{ comment.user.first_name }} {{ comment.user.last_name }}</b>, {{ comment.create_date.date }}</h4>
            <span>{{ comment.comment_text }}</span>
            <hr>
          </div>
        {% endfor %}
      {% else %}
        <h4>Be first commentator</h4>
      {% endif %}
    </div>
    <div id="comment_div" class="row">
      <div id="inner_comment_div" class="row hidden">
        <h4><b><span id="comment_username"></span></b>, <span id="comment_date"></span></h4>
        <span id="comment_text"></span>
        <hr>
      </div>
    </div>
    <div class="row">
      {% if username %}
        <form id="form_add_comment" method="post" class="form-inline" action="{% url 'add_comment' product_id=product.id %}">{% csrf_token %}
          <div class="form-group">
            <input id="user_comment_text" type="text" maxlength="300" class="form-control">
          </div>
          <div class="form-group">
            <button id="user_comment_btn" class="btn btn-primary">Comment</button>
          </div>
        </form>
      {% else %}
        <a href="{% url 'login' %}">Sign in</a> or <a href="{% url 'register' %}">sign up</a> to comment
      {% endif %}
    </div>
  </div>
{% endblock %}